# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabeza_Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2', models.TextField(blank=True)),
                ('id_c2', models.TextField(blank=True)),
                ('c3', models.CharField(max_length=1)),
                ('c4', models.TextField(blank=True)),
                ('id_c4', models.TextField(blank=True)),
                ('c4_puntaje', models.CharField(blank=True, max_length=15)),
                ('c4_folio', models.CharField(blank=True, max_length=15)),
                ('c5', models.CharField(max_length=1)),
                ('c5_beneficio', models.TextField(blank=True)),
                ('id_c5_beneficio', models.TextField(blank=True)),
                ('c6', models.CharField(max_length=1)),
                ('c6_beneficio', models.CharField(max_length=1)),
                ('c7', models.CharField(max_length=1)),
                ('c8', models.TextField(blank=True)),
                ('id_c8', models.TextField(blank=True)),
                ('c9', models.TextField(blank=True)),
                ('id_c9', models.TextField(blank=True)),
                ('c10', models.TextField(blank=True)),
                ('id_c10', models.TextField(blank=True)),
                ('c11', models.CharField(max_length=1)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Crear Cabeza de Nucleo',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(blank=True)),
                ('numero_documento', models.CharField(blank=True, max_length=15)),
                ('edad', models.CharField(blank=True, max_length=2)),
                ('sabe_leer', models.CharField(max_length=1)),
                ('sabe_escribir', models.CharField(max_length=1)),
                ('n_dias_labora', models.CharField(max_length=1)),
                ('n_horas_labora', models.CharField(max_length=1)),
                ('condiciones_especiales', models.CharField(max_length=2)),
                ('aporta_sustento', models.CharField(max_length=1)),
                ('estado_sgsss', models.CharField(max_length=1)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
                ('estado_laboral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Estado_Laboral')),
                ('nivel_escolaridad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Nivel_Escolaridad')),
                ('nombre_eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.EPS')),
                ('ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Ocupaciones')),
                ('parentezco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Parentezco')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Tipo_Documento')),
            ],
            options={
                'verbose_name_plural': 'Crear Familiar',
            },
        ),
    ]
