# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad_administradora_servicio', '0001_initial'),
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True)),
                ('f_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('f_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('allday', models.CharField(blank=True, max_length=5, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('notificacion', models.TextField(blank=True)),
                ('bandera', models.CharField(blank=True, max_length=10, null=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
                ('nota_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Notas')),
                ('uds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_administradora_servicio.UDS')),
            ],
            options={
                'verbose_name_plural': 'Crear Eventos',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('f_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('f_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('limite', models.TextField(blank=True)),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
                ('uds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidad_administradora_servicio.UDS')),
            ],
        ),
    ]
