# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='nombre',
            field=models.TextField(blank=True),
        ),
    ]
