# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas_vivienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristicasvivienda',
            name='b12',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='caracteristicasvivienda',
            name='b13',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='caracteristicasvivienda',
            name='b14',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='caracteristicasvivienda',
            name='b15',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='caracteristicasvivienda',
            name='b23',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='caracteristicasvivienda',
            name='zona_ubicacion',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
