# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-26 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadControles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.CharField(blank=True, max_length=20)),
                ('fecha', models.CharField(blank=True, max_length=10)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('fecha_control', models.CharField(max_length=10)),
                ('edad_anios', models.CharField(max_length=2)),
                ('edad_meses', models.CharField(max_length=2)),
                ('peso_kilos', models.CharField(max_length=2)),
                ('peso_gramos', models.CharField(max_length=4)),
                ('talla', models.CharField(max_length=3)),
                ('interpretacion', models.TextField(blank=True)),
                ('peso_idealK', models.CharField(blank=True, max_length=2)),
                ('peso_idealG', models.CharField(blank=True, max_length=4)),
                ('talla_ideal', models.CharField(blank=True, max_length=3)),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('clase_peso', models.CharField(blank=True, max_length=20)),
                ('clase_talla', models.CharField(blank=True, max_length=20)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toma', models.CharField(blank=True, max_length=10)),
                ('diagnostico', models.CharField(max_length=2)),
                ('examenen', models.CharField(max_length=2)),
                ('programa', models.CharField(max_length=2)),
                ('otro', models.CharField(blank=True, max_length=30)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_nacer', models.CharField(blank=True, max_length=4)),
                ('talla_nacer', models.CharField(blank=True, max_length=4)),
                ('e3', models.CharField(max_length=2)),
                ('e4', models.TextField(blank=True)),
                ('e4_f1', models.CharField(blank=True, max_length=10)),
                ('e4_f2', models.CharField(blank=True, max_length=10)),
                ('e4_f3', models.CharField(blank=True, max_length=10)),
                ('e5', models.CharField(max_length=2)),
                ('e6', models.CharField(max_length=2)),
                ('e6_otra', models.TextField(blank=True)),
                ('e7', models.CharField(max_length=2)),
                ('e7_otra', models.TextField(blank=True)),
                ('t1_d8', models.TextField(blank=True)),
                ('id_t1_d8', models.TextField(blank=True)),
                ('e1_d8', models.TextField(blank=True)),
                ('id_e1_d8', models.TextField(blank=True)),
                ('a1_d8', models.TextField(blank=True)),
                ('id_a1_d8', models.TextField(blank=True)),
                ('t2_d8', models.TextField(blank=True)),
                ('id_t2_d8', models.TextField(blank=True)),
                ('e2_d8', models.TextField(blank=True)),
                ('id_e2_d8', models.TextField(blank=True)),
                ('a2_d8', models.TextField(blank=True)),
                ('id_a2_d8', models.TextField(blank=True)),
                ('t3_d8', models.TextField(blank=True)),
                ('id_t3_d8', models.TextField(blank=True)),
                ('e3_d8', models.TextField(blank=True)),
                ('id_e3_d8', models.TextField(blank=True)),
                ('a3_d8', models.TextField(blank=True)),
                ('id_a3_d8', models.TextField(blank=True)),
                ('t4_d8', models.TextField(blank=True)),
                ('id_t4_d8', models.TextField(blank=True)),
                ('e4_d8', models.TextField(blank=True)),
                ('id_e4_d8', models.TextField(blank=True)),
                ('a4_d8', models.TextField(blank=True)),
                ('id_a4_d8', models.TextField(blank=True)),
                ('e9', models.CharField(max_length=2)),
                ('e10', models.CharField(blank=True, max_length=10)),
                ('e11', models.CharField(max_length=2)),
                ('e11_cual', models.TextField(blank=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
    ]
