# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0002_auto_20170910_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controles',
            name='grafica_peso',
        ),
        migrations.RemoveField(
            model_name='controles',
            name='grafica_talla',
        ),
    ]
