# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0004_auto_20170910_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controles',
            name='total_meses',
            field=models.BigIntegerField(blank=True),
        ),
    ]
