# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricion', '0005_auto_20170910_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controles',
            name='edad_anios',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='controles',
            name='edad_meses',
            field=models.BigIntegerField(blank=True),
        ),
    ]
