# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones_comunitarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaciones',
            name='d1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d2',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d42',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d8',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='d9',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d42',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d6',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d7',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='relaciones',
            name='id_d9',
            field=models.TextField(blank=True),
        ),
    ]
