# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='accion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='detalle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='modelo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='referencia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='logs',
            name='usuario',
            field=models.TextField(),
        ),
    ]
