# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad_administradora_servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad_administradora',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='entidad_administradora',
            name='hora',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
