# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-11 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_auto_20170910_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='edad_anios_detalle',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='edad_meses_detalle',
        ),
    ]
