# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0003_auto_20170826_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='edad_anios',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='edad_meses',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
