# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0004_auto_20170826_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='edad_anios_detalle',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='edad_meses_detalle',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
